// Code generated by ent, DO NOT EDIT.

package ent

import (
	"draw-tiles-backend/ent/tile"
	"draw-tiles-backend/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Tile is the model entity for the Tile schema.
type Tile struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,string"`
	// X holds the value of the "x" field.
	X int `json:"x,omitempty"`
	// Y holds the value of the "y" field.
	Y int `json:"y,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TileQuery when eager-loading is set.
	Edges        TileEdges `json:"edges"`
	user_tiles   *int64
	selectValues sql.SelectValues
}

// TileEdges holds the relations/edges for other nodes in the graph.
type TileEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TileEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tile.FieldID, tile.FieldX, tile.FieldY:
			values[i] = new(sql.NullInt64)
		case tile.ForeignKeys[0]: // user_tiles
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tile fields.
func (_m *Tile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case tile.FieldX:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field x", values[i])
			} else if value.Valid {
				_m.X = int(value.Int64)
			}
		case tile.FieldY:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field y", values[i])
			} else if value.Valid {
				_m.Y = int(value.Int64)
			}
		case tile.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_tiles", value)
			} else if value.Valid {
				_m.user_tiles = new(int64)
				*_m.user_tiles = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tile.
// This includes values selected through modifiers, order, etc.
func (_m *Tile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Tile entity.
func (_m *Tile) QueryUser() *UserQuery {
	return NewTileClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Tile.
// Note that you need to call Tile.Unwrap() before calling this method if this Tile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tile) Update() *TileUpdateOne {
	return NewTileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tile) Unwrap() *Tile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tile) String() string {
	var builder strings.Builder
	builder.WriteString("Tile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("x=")
	builder.WriteString(fmt.Sprintf("%v", _m.X))
	builder.WriteString(", ")
	builder.WriteString("y=")
	builder.WriteString(fmt.Sprintf("%v", _m.Y))
	builder.WriteByte(')')
	return builder.String()
}

// Tiles is a parsable slice of Tile.
type Tiles []*Tile
