// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"draw-tiles-backend/ent/predicate"
	"draw-tiles-backend/ent/tile"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TileUpdate is the builder for updating Tile entities.
type TileUpdate struct {
	config
	hooks    []Hook
	mutation *TileMutation
}

// Where appends a list predicates to the TileUpdate builder.
func (_u *TileUpdate) Where(ps ...predicate.Tile) *TileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetX sets the "x" field.
func (_u *TileUpdate) SetX(v int) *TileUpdate {
	_u.mutation.ResetX()
	_u.mutation.SetX(v)
	return _u
}

// SetNillableX sets the "x" field if the given value is not nil.
func (_u *TileUpdate) SetNillableX(v *int) *TileUpdate {
	if v != nil {
		_u.SetX(*v)
	}
	return _u
}

// AddX adds value to the "x" field.
func (_u *TileUpdate) AddX(v int) *TileUpdate {
	_u.mutation.AddX(v)
	return _u
}

// SetY sets the "y" field.
func (_u *TileUpdate) SetY(v int) *TileUpdate {
	_u.mutation.ResetY()
	_u.mutation.SetY(v)
	return _u
}

// SetNillableY sets the "y" field if the given value is not nil.
func (_u *TileUpdate) SetNillableY(v *int) *TileUpdate {
	if v != nil {
		_u.SetY(*v)
	}
	return _u
}

// AddY adds value to the "y" field.
func (_u *TileUpdate) AddY(v int) *TileUpdate {
	_u.mutation.AddY(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *TileUpdate) SetUsername(v string) *TileUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *TileUpdate) SetNillableUsername(v *string) *TileUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// Mutation returns the TileMutation object of the builder.
func (_u *TileUpdate) Mutation() *TileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TileUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := tile.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Tile.username": %w`, err)}
		}
	}
	return nil
}

func (_u *TileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tile.Table, tile.Columns, sqlgraph.NewFieldSpec(tile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.X(); ok {
		_spec.SetField(tile.FieldX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedX(); ok {
		_spec.AddField(tile.FieldX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Y(); ok {
		_spec.SetField(tile.FieldY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedY(); ok {
		_spec.AddField(tile.FieldY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(tile.FieldUsername, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TileUpdateOne is the builder for updating a single Tile entity.
type TileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TileMutation
}

// SetX sets the "x" field.
func (_u *TileUpdateOne) SetX(v int) *TileUpdateOne {
	_u.mutation.ResetX()
	_u.mutation.SetX(v)
	return _u
}

// SetNillableX sets the "x" field if the given value is not nil.
func (_u *TileUpdateOne) SetNillableX(v *int) *TileUpdateOne {
	if v != nil {
		_u.SetX(*v)
	}
	return _u
}

// AddX adds value to the "x" field.
func (_u *TileUpdateOne) AddX(v int) *TileUpdateOne {
	_u.mutation.AddX(v)
	return _u
}

// SetY sets the "y" field.
func (_u *TileUpdateOne) SetY(v int) *TileUpdateOne {
	_u.mutation.ResetY()
	_u.mutation.SetY(v)
	return _u
}

// SetNillableY sets the "y" field if the given value is not nil.
func (_u *TileUpdateOne) SetNillableY(v *int) *TileUpdateOne {
	if v != nil {
		_u.SetY(*v)
	}
	return _u
}

// AddY adds value to the "y" field.
func (_u *TileUpdateOne) AddY(v int) *TileUpdateOne {
	_u.mutation.AddY(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *TileUpdateOne) SetUsername(v string) *TileUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *TileUpdateOne) SetNillableUsername(v *string) *TileUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// Mutation returns the TileMutation object of the builder.
func (_u *TileUpdateOne) Mutation() *TileMutation {
	return _u.mutation
}

// Where appends a list predicates to the TileUpdate builder.
func (_u *TileUpdateOne) Where(ps ...predicate.Tile) *TileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TileUpdateOne) Select(field string, fields ...string) *TileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tile entity.
func (_u *TileUpdateOne) Save(ctx context.Context) (*Tile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TileUpdateOne) SaveX(ctx context.Context) *Tile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TileUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := tile.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Tile.username": %w`, err)}
		}
	}
	return nil
}

func (_u *TileUpdateOne) sqlSave(ctx context.Context) (_node *Tile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tile.Table, tile.Columns, sqlgraph.NewFieldSpec(tile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tile.FieldID)
		for _, f := range fields {
			if !tile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.X(); ok {
		_spec.SetField(tile.FieldX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedX(); ok {
		_spec.AddField(tile.FieldX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Y(); ok {
		_spec.SetField(tile.FieldY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedY(); ok {
		_spec.AddField(tile.FieldY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(tile.FieldUsername, field.TypeString, value)
	}
	_node = &Tile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
