// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"draw-tiles-backend/ent/tile"
	"draw-tiles-backend/ent/user"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TileCreate is the builder for creating a Tile entity.
type TileCreate struct {
	config
	mutation *TileMutation
	hooks    []Hook
}

// SetX sets the "x" field.
func (_c *TileCreate) SetX(v int) *TileCreate {
	_c.mutation.SetX(v)
	return _c
}

// SetY sets the "y" field.
func (_c *TileCreate) SetY(v int) *TileCreate {
	_c.mutation.SetY(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TileCreate) SetID(v int64) *TileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TileCreate) SetUserID(id int64) *TileCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *TileCreate) SetNillableUserID(id *int64) *TileCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TileCreate) SetUser(v *User) *TileCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TileMutation object of the builder.
func (_c *TileCreate) Mutation() *TileMutation {
	return _c.mutation
}

// Save creates the Tile in the database.
func (_c *TileCreate) Save(ctx context.Context) (*Tile, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TileCreate) SaveX(ctx context.Context) *Tile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TileCreate) check() error {
	if _, ok := _c.mutation.X(); !ok {
		return &ValidationError{Name: "x", err: errors.New(`ent: missing required field "Tile.x"`)}
	}
	if _, ok := _c.mutation.Y(); !ok {
		return &ValidationError{Name: "y", err: errors.New(`ent: missing required field "Tile.y"`)}
	}
	return nil
}

func (_c *TileCreate) sqlSave(ctx context.Context) (*Tile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TileCreate) createSpec() (*Tile, *sqlgraph.CreateSpec) {
	var (
		_node = &Tile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tile.Table, sqlgraph.NewFieldSpec(tile.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.X(); ok {
		_spec.SetField(tile.FieldX, field.TypeInt, value)
		_node.X = value
	}
	if value, ok := _c.mutation.Y(); ok {
		_spec.SetField(tile.FieldY, field.TypeInt, value)
		_node.Y = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tile.UserTable,
			Columns: []string{tile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_tiles = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TileCreateBulk is the builder for creating many Tile entities in bulk.
type TileCreateBulk struct {
	config
	err      error
	builders []*TileCreate
}

// Save creates the Tile entities in the database.
func (_c *TileCreateBulk) Save(ctx context.Context) ([]*Tile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TileCreateBulk) SaveX(ctx context.Context) []*Tile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
