// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TilesColumns holds the columns for the "tiles" table.
	TilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "x", Type: field.TypeInt},
		{Name: "y", Type: field.TypeInt},
		{Name: "username", Type: field.TypeString},
		{Name: "user_tiles", Type: field.TypeInt64, Nullable: true},
	}
	// TilesTable holds the schema information for the "tiles" table.
	TilesTable = &schema.Table{
		Name:       "tiles",
		Columns:    TilesColumns,
		PrimaryKey: []*schema.Column{TilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tiles_users_tiles",
				Columns:    []*schema.Column{TilesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tile_x_y",
				Unique:  true,
				Columns: []*schema.Column{TilesColumns[1], TilesColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TilesTable,
		UsersTable,
	}
)

func init() {
	TilesTable.ForeignKeys[0].RefTable = UsersTable
}
