// Code generated by ent, DO NOT EDIT.

package tile

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tile type in the database.
	Label = "tile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldX holds the string denoting the x field in the database.
	FieldX = "x"
	// FieldY holds the string denoting the y field in the database.
	FieldY = "y"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// Table holds the table name of the tile in the database.
	Table = "tiles"
)

// Columns holds all SQL columns for tile fields.
var Columns = []string{
	FieldID,
	FieldX,
	FieldY,
	FieldUsername,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tiles"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_tiles",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
)

// OrderOption defines the ordering options for the Tile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByX orders the results by the x field.
func ByX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldX, opts...).ToFunc()
}

// ByY orders the results by the y field.
func ByY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldY, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}
