// Code generated by ent, DO NOT EDIT.

package tile

import (
	"draw-tiles-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Tile {
	return predicate.Tile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Tile {
	return predicate.Tile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Tile {
	return predicate.Tile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Tile {
	return predicate.Tile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Tile {
	return predicate.Tile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Tile {
	return predicate.Tile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Tile {
	return predicate.Tile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Tile {
	return predicate.Tile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Tile {
	return predicate.Tile(sql.FieldLTE(FieldID, id))
}

// X applies equality check predicate on the "x" field. It's identical to XEQ.
func X(v int) predicate.Tile {
	return predicate.Tile(sql.FieldEQ(FieldX, v))
}

// Y applies equality check predicate on the "y" field. It's identical to YEQ.
func Y(v int) predicate.Tile {
	return predicate.Tile(sql.FieldEQ(FieldY, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Tile {
	return predicate.Tile(sql.FieldEQ(FieldUsername, v))
}

// XEQ applies the EQ predicate on the "x" field.
func XEQ(v int) predicate.Tile {
	return predicate.Tile(sql.FieldEQ(FieldX, v))
}

// XNEQ applies the NEQ predicate on the "x" field.
func XNEQ(v int) predicate.Tile {
	return predicate.Tile(sql.FieldNEQ(FieldX, v))
}

// XIn applies the In predicate on the "x" field.
func XIn(vs ...int) predicate.Tile {
	return predicate.Tile(sql.FieldIn(FieldX, vs...))
}

// XNotIn applies the NotIn predicate on the "x" field.
func XNotIn(vs ...int) predicate.Tile {
	return predicate.Tile(sql.FieldNotIn(FieldX, vs...))
}

// XGT applies the GT predicate on the "x" field.
func XGT(v int) predicate.Tile {
	return predicate.Tile(sql.FieldGT(FieldX, v))
}

// XGTE applies the GTE predicate on the "x" field.
func XGTE(v int) predicate.Tile {
	return predicate.Tile(sql.FieldGTE(FieldX, v))
}

// XLT applies the LT predicate on the "x" field.
func XLT(v int) predicate.Tile {
	return predicate.Tile(sql.FieldLT(FieldX, v))
}

// XLTE applies the LTE predicate on the "x" field.
func XLTE(v int) predicate.Tile {
	return predicate.Tile(sql.FieldLTE(FieldX, v))
}

// YEQ applies the EQ predicate on the "y" field.
func YEQ(v int) predicate.Tile {
	return predicate.Tile(sql.FieldEQ(FieldY, v))
}

// YNEQ applies the NEQ predicate on the "y" field.
func YNEQ(v int) predicate.Tile {
	return predicate.Tile(sql.FieldNEQ(FieldY, v))
}

// YIn applies the In predicate on the "y" field.
func YIn(vs ...int) predicate.Tile {
	return predicate.Tile(sql.FieldIn(FieldY, vs...))
}

// YNotIn applies the NotIn predicate on the "y" field.
func YNotIn(vs ...int) predicate.Tile {
	return predicate.Tile(sql.FieldNotIn(FieldY, vs...))
}

// YGT applies the GT predicate on the "y" field.
func YGT(v int) predicate.Tile {
	return predicate.Tile(sql.FieldGT(FieldY, v))
}

// YGTE applies the GTE predicate on the "y" field.
func YGTE(v int) predicate.Tile {
	return predicate.Tile(sql.FieldGTE(FieldY, v))
}

// YLT applies the LT predicate on the "y" field.
func YLT(v int) predicate.Tile {
	return predicate.Tile(sql.FieldLT(FieldY, v))
}

// YLTE applies the LTE predicate on the "y" field.
func YLTE(v int) predicate.Tile {
	return predicate.Tile(sql.FieldLTE(FieldY, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Tile {
	return predicate.Tile(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Tile {
	return predicate.Tile(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Tile {
	return predicate.Tile(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Tile {
	return predicate.Tile(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Tile {
	return predicate.Tile(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Tile {
	return predicate.Tile(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Tile {
	return predicate.Tile(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Tile {
	return predicate.Tile(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Tile {
	return predicate.Tile(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Tile {
	return predicate.Tile(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Tile {
	return predicate.Tile(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Tile {
	return predicate.Tile(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Tile {
	return predicate.Tile(sql.FieldContainsFold(FieldUsername, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tile) predicate.Tile {
	return predicate.Tile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tile) predicate.Tile {
	return predicate.Tile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tile) predicate.Tile {
	return predicate.Tile(sql.NotPredicates(p))
}
